name: Mike Lewis
favicon: null
layout_spectrum: 0.4927413333207369
typography_spectrum: 0.9056225412059575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3330346653237939
  lightness: 0.5830921563319862
  saturation: 0.7887374442070723
  rhythmicContrast: 0.567520105978474
purpose: []
