name: Mike Lewis
favicon: null
layout_spectrum: 0.49542
typography_spectrum: 0.45952
title: Mike Lewis
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2b3c4f'
    - '#ebf0ec'
    - '#caa987'
    - '#6095c8'
    - '#eb4b38'
  brandStrength: 0.3330346653237939
  lightness: 0.5830921563319862
  saturation: 0.7887374442070723
  rhythmicContrast: 0.567520105978474
purpose: []
